name: Issue Workflow
on: issues
jobs:
  issue_info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Issue Event Info
        run: echo "The issue event action is ${{ toJson(github.event) }} "
      - name: Output Full Github Context
        run: echo "Github ${{ toJson(github) }}."