name: Lint and Deploy
on: [push, pull_request]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: 18
            - name: Install dependencies
              run: npm install
            - name: Run ESLint
              run: npx eslint . --ext .js,.jsx
    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: 18
            - name: Install dependencies
              run: npm install
            - name: Execute tests
              run: npm test
    deploy:
        needs: test
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        steps:
           - uses: actions/checkout@v2
           - name: Set up Node.js
             uses: actions/setup-node@v2
             with:
                node-version: 18
           - name: Install dependencies
             run: npm install
           - name: Build project
             run: npm run build
           - name: Deploy to GitHub Pages
             uses: peaceiris/actions-gh-pages@v3
             with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./build
           - name: Deploy Project
             run: |
                echo "Deployed to production..."